name: Build qView
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      isRelease:
        type: boolean
        description: 'Is this a release build?'
        required: false
        default: false
jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: 'ubuntu-20.04'
            qtVersion: '5.15.2'
          - runner: 'macos-latest'
            qtVersion: '6.5.3'
            qtModules: 'qtimageformats'
          - runner: 'macos-latest'
            qtVersion: '5.15.2'
            osSuffix: '_legacy'
          - runner: 'windows-2019'
            qtVersion: '6.5.3'
            qtArch: 'win64_msvc2019_64'
            osSuffix: '_64'
            qtModules: 'qtimageformats'
          - runner: 'windows-2019'
            qtVersion: '5.15.2'
            qtArch: 'win32_msvc2019'
            osSuffix: '_32'
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set environment variables
        shell: bash
        run: |
          echo "arch=${{ matrix.qtArch }}" >> $GITHUB_ENV
          if [ "${{ inputs.isRelease }}" != "true" ]; then
            buildNum=$(date '+%Y-%m-%d').${GITHUB_SHA::7}
            echo "nightlyDefines=NIGHTLY=$buildNum" >> $GITHUB_ENV
            echo "buildNumString=$buildNum" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qtVersion }}
          arch: ${{ matrix.qtArch }}
          cache: true
          modules: ${{ matrix.qtModules }}

      - name: Build qView
        shell: pwsh
        run: dist/scripts/build.ps1

      - name: Deploy qView
        shell: pwsh
        run: |
          if ("${{ matrix.skipPlugins }}" -ne "true") {
            Invoke-Expression "& 'dist/scripts/download-plugins.ps1'"
          }
          if ($IsWindows) {
            Invoke-Expression "& 'dist/scripts/windeployqt.ps1' ${{ env.buildNumString }}"
          } elseif ($IsMacOS) {
            bash dist/scripts/macdeploy.sh ${{ env.buildNumString }} ${{ matrix.osSuffix }}
          } else {
            bash dist/scripts/linuxdeployqt.sh ${{ env.buildNumString }}
          }

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: qView-JDP${{ env.buildNumString != '' && '-' || '' }}${{ env.buildNumString }}-${{ runner.os }}${{ matrix.osSuffix }}
          path: bin
